### ISSUE TITLE
pulls wrong / static version of APB

### ISSUE THREAD

**Issue by scarstens** [WordPress-Phoenix/wordpress-development-toolkit#5]
should ping and pull down "latest" version of APB:
https://github.com/WordPress-Phoenix/abstract-plugin-base/releases/latest

Workaround is to delete the LIB folder and then ```composer update --no-dev --no-autoloader```

**Comment by scarstens** [comment]
note on this that it would have to generate the proper namespace:
```use WPAZ_Plugin_Base\V_2_5\Abstract_Plugin;```

**Comment by 0aveRyan** [comment]
pulling from gh api now
