### ISSUE TITLE
no admin interface

### ISSUE THREAD

**Issue by quasiperfect** [WordPress-Phoenix/wordpress-development-toolkit#8]
hi when i click the /wp-admin/admin.php?page=wp-phx-dev-kit i just get a page with  "awwyiss"
and that's all. what i'm doing wrong ?

**Comment by scarstens** [comment]
thats odd, do you want to send in a screenshot?

**Comment by scarstens** [comment]
actually looking at it, most of this page is generated as javascript. most likely you have a JS conflict. Maybe try installing this plugin on a vanilla wordpress site and use it there? I'm guessing you have another plugin or theme thats injecting bad / conflicting javascript @quasiperfect

**Comment by quasiperfect** [comment]
@scarstens clean wp install

in console i get a 404 on http://wordpress.oo/wp-content/plugins/wordpress-development-toolkit-master/app/app/admin/js/dashboard.js?ver=84463182

for some reason i see it ads a extra app to the path.
i'm testing on windows latest version of laragon server

**Comment by scarstens** [comment]
can you try renaming the plugin folder to `wordpress-development-toolkit` instead of what you have? the folder name does matter.

**Comment by quasiperfect** [comment]
@scarstens yes it works thanks
